
server: 
  port: 8080
  ssl:
    ciphers: EECDH+ECDSA+AESGCM,EECDH+aRSA+AESGCM,EECDH+ECDSA+SHA512,EECDH+ECDSA+SHA384,EECDH+ECDSA+SHA256,ECDH+AESGCM,ECDH+AES256,DH+AESGCM,DH+AES256,RSA+AESGCM,!aNULL,!eNULL,!LOW,!RC4,!3DES,!MD5,!EXP,!PSK,!SRP,!DSS
    enabled: false
    enabled-protocols: TLSv1.2,TLSv1.1,TLSv1
    key-alias: haud-authsrv
    key-store: /home/matthew-haud/NetBeansProjects/oauth2-service/extra/haud-authsrv.jks
    key-store-password: iKj9lnZU
    key-store-type: pkcs12
    protocol: TLS
spring:
  application:
    name: oauth2-server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password:
    platform: org.hibernate.dialect.MySQL8DBDialect
    url: jdbc:mysql://localhost:3306/OAUTH2_SERVICE_LDAP?serverTimezone=UTC&useSSL=true
    username: root
	  password: root
    intialize: true
    dbcp2:
      maxTotal: 2
      connectionInitSqls: select 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none 
      defaultSchema: OAUTH2_SERVICE_LDAP
  profiles:
    active: springLdap
resources:
  static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/**
authsvc:
  ldap:
    provider:
      url: ldap://191.255.15.251:389
      auth:
        fullUserDn: CN=Administrator,CN=Users,DC=matfar,DC=haud
        password: duHasoPssY123!
    search:
      userSearchBase: CN=Users,DC=matfar,DC=haud
      userSearchFilter: (&(sAMAccountName={0}))
      groupSearchBase: CN=Users,DC=matfar,DC=haud
      groupSearchFilter: (&(member={0})(objectClass=group)) 
      groupRoleAttribute: cn
      groupSearchSubtree: true
  authorities:
    cacheRefreshInterval: 10000
  wellKnown:
    authorisationEndpoint: http://localhost:8080/oauth/authorize
    tokenEndpoint: http://localhost:8080/oauth/token
    userInfoEndpoint: http://localhost:8080/opic/userinfo
    revocationEndpoint: http://localhost:8080/opic/revoke
    jwksEndpoint: http://localhost:8080/opic/certs
  refreshTokens:
    expiredCleanupInterval: 60000
  security:
    keystorePath: /home/matthew-haud/NetBeansProjects/oauth2-service/extra/haud-authsrv.jks
    keystorePass: iKj9lnZU
    keyAlias: haud-authsrv  
  internalAudience: localhost
  defaultRedirectUrl: http://haud.com
security:
  oauth2:
    resource:
      filter-order: 3
  audit:
    enabled: false  
logging:
  level:
    org:
      springframework:
        security: debug
    com:
      haud: debug
audit:
  service:
    url: http://localhost/
